openapi: 3.0.0
info:
  title: Liquid Galaxy Control API
  description: REST API for controlling and managing Liquid Galaxy systems via SSH
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server

components:
  schemas:
    AppSuccess:
      type: object
      properties:
        message:
          type: string
          description: Success message
        statusCode:
          type: integer
          description: HTTP status code
          example: 200
        data:
          type: string
          description: Empty string
          example: ""

    AppError:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "An error occurred"
        statusCode:
          type: integer
          description: HTTP status code
          example: 400
        stack:
          type: string
          description: Error stack trace
          example: ""

    BasicSSHConfig:
      type: object
      required:
        - ip
        - port
        - username
        - password
      properties:
        ip:
          type: string
          description: SSH host IP address
          example: "192.168.201.3"
        port:
          type: string
          description: SSH port number
          example: "22"
        username:
          type: string
          description: SSH username
          example: "lg"
        password:
          type: string
          description: SSH password
          format: password
          example: "lg"
    
    RigConfig:
      allOf:
        - $ref: '#/components/schemas/BasicSSHConfig'
        - type: object
          required:
            - rigs
          properties:
            rigs:
              type: string
              description: Number of Liquid Galaxy rigs
              example: "3"
    
    FlyToConfig:
      allOf:
        - $ref: '#/components/schemas/RigConfig'
        - type: object
          required:
            - latitude
            - longitude
            - tilt
            - elevation
            - bearing
          properties:
            latitude:
              type: string
              description: Target latitude
              example: "40.7128"
            longitude:
              type: string
              description: Target longitude
              example: "-74.0060"
            elevation:
              type: string
              description: Camera elevation with LG zoom
              example: "12000"  
            tilt:
              type: string
              description: Camera tilt angle
              example: "45"
            bearing:
              type: string
              description: Camera bearing
              example: "0"

    LogoConfig:
      allOf:
        - $ref: '#/components/schemas/RigConfig'
        - type: object
          required:
            - kml
          properties:
            kml:
              type: string
              description: KML content for the logo
              example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><kml>...</kml>"

    BalloonConfig:
      allOf:
        - $ref: '#/components/schemas/RigConfig'
        - type: object
          required:
            - kml
          properties:
            kml:
              type: string
              description: KML content for the balloon
              example: "<kml>...</kml>"

paths:
  /lg-connection/check-connection:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Check connection status
      description: Establishes an SSH connection to the Liquid Galaxy system using the provided credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSSHConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/connect-lg:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Connects to Liquid Galaxy Rigs
      description: Establishes an SSH connection to the Liquid Galaxy system using the provided credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSSHConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/execute-orbit:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Execute orbit visualization
      description: Initiates an orbital visualization around the current view in Liquid Galaxy.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlyToConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/clean-visualization:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Clean visualization resources
      description: Cleans up all active visualizations in Liquid Galaxy.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSSHConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/clean-logos:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Clean logo resources
      description: Removes all logo overlays from the left-most rig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/relaunch-lg:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Relaunch Liquid Galaxy
      description: Restarts the Liquid Galaxy application software without rebooting the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/reboot-lg:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Reboot Liquid Galaxy
      description: Performs a complete system reboot of all Liquid Galaxy machines.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
  
  /lg-connection/shutdown-lg:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Shutdown Liquid Galaxy Rigs 
      description: Shuts down all Liquid Galaxy machines, powering off the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'              

  /lg-connection/stop-orbit:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Stop orbit visualization
      description: Halts any currently active orbital visualization movement.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSSHConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/clean-balloon:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Clean balloon resources
      description: Removes all information balloons from the right-most rig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/flyto:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Fly to specific coordinates
      description: Animates the view to fly to specified geographic coordinates with custom viewing angles.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlyToConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/show-logo:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Display logo on screen
      description: Displays a logo on the left-most rig using KML
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/show-balloon:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Display balloon on screen
      description: Shows an information balloon on the right-most rig using KML
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalloonConfig'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'

  /lg-connection/send-kml:
    post:
      tags:
        - Liquid Galaxy Controls
      summary: Send KML file
      description: Uploads and displays a custom KML file on the Liquid Galaxy system.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: file to upload (.txt)
                ip:
                  type: string
                  description: Ip Address (eg. 192.168.201.1)
                port:
                  type: string
                  description: port (eg. 22)
                username:
                  type: string
                  description: userName (eg. lg)
                password:
                  type: string
                  format: password
                  description: password (eg. lg)
                filename:
                  type: string
                  description: Name of the file (eg. test)
              required:
                - file
                - ip
                - port
                - username
                - password
                - filename
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSuccess'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'